<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/5/16
 * Time: 11:11
 */

namespace Email;


class Email extends AbstractEmail
{
    public function build()
    {
        // TODO: Implement build() method.
    }

    public function send()
    {
        parent::send(); // TODO: Change the autogenerated stub
    }
}